### PR TITLE
replace lazy_static with std's OnceLock

### PR DESCRIPTION
**Pull request by Liyixin95**
The `once_cell` has been stable in std, and the 'lazy_static' is going to be deprecated, so it's better to use std's `once_cell` instead of `lazy_static`.

check detail at : https://github.com/rust-lang-nursery/lazy-static.rs/issues/214

### CODE REVIEW

**Comment by Millione** [comment]
How about using LazyLock?

**Comment by Liyixin95** [comment]
> How about using LazyLock?

`LazyLock` is newly introduced to std in `1.80`. So using `LazyLock` will bump the msrv up to `1.80`.

**Comment by Liyixin95** [comment]
> How about using LazyLock?

There are three choice:
1. use `OnceLock`, which is little more verbose
2. use std's `LazyLock`, which will bump up the msrv
3. use the `LazyLock` in `once_cell`.

You maintainer can make a decision and I will follow.

**Comment by PureWhiteWu** [comment]
Thanks very much for your contribution!
I think that using OnceLock seems really a little verbose, so maybe we can use `LazyLock` and bump the MSRV?
Bumping MSRV is not considered as a breaking change.

**Comment by Liyixin95** [comment]
> Thanks very much for your contribution! I think that using OnceLock seems really a little verbose, so maybe we can use `LazyLock` and bump the MSRV? Bumping MSRV is not considered as a breaking change.

done

**Review by yukiiiteru — APPROVED** [review]

**Review by PureWhiteWu — APPROVED** [review]

**Pull request merged**
