### PR TITLE
feat: optimize volo-grpc codec decode poll_next fn

### PR DESCRIPTION
**Pull request by daheige**
Readability of code: optimize volo-grpc codec decode poll_next fn

### CODE REVIEW

**Comment by PureWhiteWu** [comment]
Thanks for your contribution!
I'm not quite sure this can improve the readability, would you like to take a look at this? @LYF1999 @Millione

**Comment by PureWhiteWu** [comment]
Furthermore, could you please sign the CLA? Thanks. @daheige

**Comment by Millione** [comment]
@daheige I can hardly see the benefit of writing in this way. Maybe you can give a more detailed description about why?

As I can describe, `unwrap()` should be avoided as much as possible, this will cause our program less robust.

**Comment by PureWhiteWu** [comment]
Using `if let` is more conventional in Rust, and this can decrease usage of `unwrap`.
Also, it may have to do with the habits of each team (and each individual), and we think using `if let` is a better way in Rust.
Anyway, thanks for your contribution again!

**Comment by daheige** [comment]
> Using `if let` is more conventional in Rust, and this can decrease usage of `unwrap`. Also, it may have to do with the habits of each team (and each individual), and we think using `if let` is a better way in Rust. Anyway, thanks for your contribution again!

maybe.But is_err(),is_none(),it is better to handle the relevant logic in advance. Also I don't think what you guys are saying is the best way to deal with it. To your point of view, I just say, huh, huh,just so so.

**Comment by daheige** [comment]
The readability and logic here look clearer and clearer than before. There is also no need to worry about unwrap. In the past five years, relevant judgments have been made.


------------------ Original ------------------
From: LIU JIE ***@***.***&gt;
Date: Thu,Sep 22,2022 11:02 AM
To: cloudwego/volo ***@***.***&gt;
Cc: heige ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [cloudwego/volo] feat: optimize volo-grpc codec decode poll_next fn (PR #36)





 
@daheige I can hardly see the benefit of writing in this way. Maybe you can give a more detailed description about why?
 
As I can describe, unwrap() should be avoided as much as possible, this will cause our program less robust.

**Pull request closed without merging**
